"""
cdktf_runner.py

The Execution Sandbox (Phase 3). The DevOps Agent never writes raw
Terraform/HCL strings. Instead it calls write_resize_config(), which
generates a structured CDKTF Python stack file deterministically (the LLM
only chose WHICH service/instance_type via the validated Pydantic model in
guardrails.py -- it never touches this file's content directly).

run_cdktf_plan() then either:
  (a) shells out to the real `cdktf plan` if CDKTF + Terraform are installed
      (set CDKTF_REAL=1 in the environment), or
  (b) runs a deterministic local syntax/logic check that mimics what a real
      plan would catch (unknown instance type, no-op resize, etc.) so the
      whole pipeline works with zero extra installs.

apply_resize() commits the change to sandbox/applied_resizes.json, which
telemetry_generator.py watches and reacts to -- this is the closed feedback
loop described in Phase 4.
"""

import json
import os
import subprocess

from guardrails import ALLOWED_INSTANCE_TYPES, record_modification

SANDBOX_DIR = os.path.dirname(__file__)
STACK_FILE = os.path.join(SANDBOX_DIR, "cdktf_app", "main.py")
APPLIED_RESIZES_PATH = os.path.join(SANDBOX_DIR, "applied_resizes.json")

CDKTF_REAL = os.environ.get("CDKTF_REAL", "0") == "1"

STACK_TEMPLATE = '''"""
AUTO-GENERATED by the DevOps Agent. Do not hand-edit.
Represents the desired infrastructure state for service: {service_id}
"""
from cdktf import App, TerraformStack
from constructs import Construct


class FinOpsStack(TerraformStack):
    def __init__(self, scope: Construct, ns: str):
        super().__init__(scope, ns)
        # Mock "aws_instance"-style resource block. In a real deployment this
        # would be cdktf-cdktf-provider-aws's Instance() construct.
        self.service_id = "{service_id}"
        self.instance_type = "{instance_type}"


app = App()
FinOpsStack(app, "{service_id}-stack")
app.synth()
'''


def write_resize_config(service_id: str, instance_type: str):
    """Step 3.2: deterministically write/overwrite the CDKTF stack file
    representing this one resize action."""
    os.makedirs(os.path.dirname(STACK_FILE), exist_ok=True)
    with open(STACK_FILE, "w") as f:
        f.write(STACK_TEMPLATE.format(service_id=service_id, instance_type=instance_type))
    print(f"[cdktf_runner] wrote stack config for {service_id} -> {instance_type}")


def _simulated_plan_check(service_id: str, instance_type: str) -> dict:
    """Deterministic stand-in for `cdktf plan` syntax/logic validation.
    Mirrors real failure modes: unknown type, empty service id, etc."""
    if instance_type not in ALLOWED_INSTANCE_TYPES:
        return {"success": False, "error": f"Unknown instance_type '{instance_type}' "
                                            f"not in allowed catalog."}
    if not service_id or not service_id.strip():
        return {"success": False, "error": "service_id is empty -- invalid resource address."}
    if not os.path.exists(STACK_FILE):
        return {"success": False, "error": "Stack file missing -- write_resize_config() "
                                            "must run before plan."}
    return {"success": True, "error": None,
            "summary": f"Plan: 1 to change, 0 to add, 0 to destroy ({service_id} -> {instance_type})"}


def run_cdktf_plan() -> dict:
    """Step 3.3: verification layer. Tries real `cdktf plan` if enabled and
    available; otherwise uses the deterministic simulated check so the demo
    runs with zero extra installs."""
    if CDKTF_REAL:
        try:
            result = subprocess.run(
                ["cdktf", "plan"],
                cwd=os.path.join(SANDBOX_DIR, "cdktf_app"),
                capture_output=True, text=True, timeout=120,
            )
            if result.returncode == 0:
                return {"success": True, "error": None, "summary": result.stdout[-500:]}
            return {"success": False, "error": result.stderr[-1000:] or result.stdout[-1000:]}
        except FileNotFoundError:
            print("[cdktf_runner] cdktf CLI not found, falling back to simulated plan")
        except Exception as e:
            print(f"[cdktf_runner] real cdktf plan errored ({e}), falling back to simulated plan")

    # Parse what we just wrote, to keep the simulated check honest
    with open(STACK_FILE) as f:
        content = f.read()
    import re
    sid_match = re.search(r'self\.service_id = "(.*?)"', content)
    type_match = re.search(r'self\.instance_type = "(.*?)"', content)
    service_id = sid_match.group(1) if sid_match else ""
    instance_type = type_match.group(1) if type_match else ""

    return _simulated_plan_check(service_id, instance_type)


def apply_resize(service_id: str, instance_type: str, db_config: dict):
    """Step 4.1: simulate deployment by updating the shared
    applied_resizes.json file that the telemetry generator watches, and
    start this service's cooldown clock in TimescaleDB."""
    applied = {}
    if os.path.exists(APPLIED_RESIZES_PATH):
        try:
            with open(APPLIED_RESIZES_PATH, "r") as f:
                applied = json.load(f)
        except json.JSONDecodeError:
            applied = {}

    applied[service_id] = instance_type
    with open(APPLIED_RESIZES_PATH, "w") as f:
        json.dump(applied, f, indent=2)

    record_modification(service_id, db_config)
    print(f"[cdktf_runner] APPLIED: {service_id} -> {instance_type} "
          f"(cooldown started, telemetry generator will pick this up on next tick)")
